### ISSUE TITLE
Can't install in Node v0.11.14

### ISSUE THREAD

**Issue by q2dg** [turingou/player#26]
Node-gyp gives some errors. One of them can be solved changing dependency version of node-speaker module in package.json from 0.0.10 to 0.2.1 (current). The other is related to node-lame module, wich can't be solved at the moment (see https://github.com/TooTallNate/node-lame/issues/27)...but I wanted to make reference here

**Comment by turingou** [comment]
Hi @q2dg player module branch `master` has been updated to latest version of `node-speaker` and `node-lame`, which both are support node `v0.12.x`, you could check out branch master and test again. 

These changes will be shipped in next version `v0.4.0`
