### ISSUE TITLE
depends on Speaker - which is not compatible with node 0.12 (?)

### ISSUE THREAD

**Issue by KimWeldon** [turingou/player#34]
..\src\binding.cc(131): error C2661: 'v8::Object::Set' : no overloaded function takes 3 arguments

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Anonymous\nodeBundle\node_modules\player\node_modules\speaker
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

**Comment by turingou** [comment]
Hi @KimWeldon player module branch `master` has been updated to latest version of `node-speaker` and `node-lame`, which both are support node `v0.12.x`, you could check out branch master and test again. 

These changes will be shipped in next version `v0.4.0`
