### ISSUE TITLE
Unhandled error event

### ISSUE THREAD

**Issue by jm21** [turingou/player#38]
I cant seem to get the demo to work. Am using node on raspberry pi, I've set up the following code: 

`var Player = require('player');
var pkg = require('../package.json');
var debug = require('debug')(pkg.name);

var player = new Player('http://stream.srg-ssr.ch/m/rsp/mp3_128', {
  stream: true
});

player.play();

player.on('playing', function(song) {
  debug('Playing... ');
  debug(song);
});

player.on('error', function(err) {
  debug('Opps...!')
  debug(err);
});

Am getting the following error when trying to run node index.js

Error: ENOENT, open 'mp3_128'
at Error (native)

Any ideas on whats wrong?

**Comment by turingou** [comment]
`ENOENT` error may be a file opening error or network error.
It seems `npm run example-stream` works well to me.

**Comment by turingou** [comment]
Could you please check the third party dependencies in your raspberry pi
If problems did not solved, feel free to reopen the issue
